import { act, renderHook } from '@testing-library/react'
import { beforeEach, expect, it, vi } from 'vitest'
import { useConcierge } from '@/features/concierge/useConcierge'
import type { ConciergeResponseEnvelope, MealProposal } from '@/features/concierge/types'
const mocks = vi.hoisted(() => ({ chat: vi.fn(), action: vi.fn(), auth: undefined as undefined | ((event: string, session: { user: { id: string } } | null) => void) }))
vi.mock('@/features/concierge/api', () => ({ sendConciergeChat: mocks.chat, sendConciergeAction: mocks.action, sendConciergeFeedback: vi.fn() }))
vi.mock('@/lib/supabase', () => ({ supabase: { auth: { onAuthStateChange: (callback: typeof mocks.auth) => { mocks.auth = callback; return { data: { subscription: { unsubscribe: vi.fn() } } } } } } }))
vi.mock('@/store/cart', () => ({ useCart: () => ({ add: vi.fn(), setCartOpen: vi.fn() }) }))
const response = (id: string): ConciergeResponseEnvelope => ({ conversation_id: id, session_token: id, state_version: 2, intent: 'general_chat', current_step: 'IDLE', message: id, cards: [], warnings: [], suggested_actions: ['private suggestion'], references: [] })
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>((yes) => { resolve = yes }); return { resolve, promise } }
beforeEach(() => { vi.clearAllMocks(); mocks.chat.mockResolvedValue(response('old')) })
it('clears and locks reset synchronously, serializes duplicate resets, and ignores old completions', async () => {
  const { result } = renderHook(() => useConcierge())
  await act(async () => { await result.current.sendMessage('hello') })
  const pending = deferred<ConciergeResponseEnvelope>(); mocks.action.mockReturnValue(pending.promise)
  let reset!: Promise<void>
  await act(async () => { reset = result.current.resetConversation(); void result.current.resetConversation(); void result.current.sendMessage('blocked'); void result.current.sendAction({ type: 'confirm_quote' }) })
  expect(mocks.action).toHaveBeenCalledTimes(1)
  expect(mocks.chat).toHaveBeenCalledTimes(1)
  expect(result.current.conversationId).toBeNull()
  expect(result.current.isLoading).toBe(true)
  expect(result.current.suggestedActions).not.toContain('private suggestion')
  await act(async () => { pending.resolve(response('reset')); await reset })
  expect(result.current.isLoading).toBe(false)
})
it('auth identity changes invalidate reset without letting its finally clear or unlock a new request', async () => {
  const { result } = renderHook(() => useConcierge())
  act(() => mocks.auth!('SIGNED_IN', { user: { id: 'a' } }))
  await act(async () => { await result.current.sendMessage('hello') })
  const pendingReset = deferred<ConciergeResponseEnvelope>(); mocks.action.mockReturnValue(pendingReset.promise)
  let reset!: Promise<void>; act(() => { reset = result.current.resetConversation() })
  act(() => mocks.auth!('SIGNED_IN', { user: { id: 'b' } }))
  const pendingChat = deferred<ConciergeResponseEnvelope>(); mocks.chat.mockReturnValue(pendingChat.promise)
  let chat!: Promise<void>; act(() => { chat = result.current.sendMessage('new account') })
  expect(mocks.chat.mock.calls.at(-1)?.[0].conversation_id).toBeUndefined()
  await act(async () => { pendingReset.resolve(response('reset')); await reset })
  expect(result.current.isLoading).toBe(true)
  expect(result.current.messages.at(-1)?.text).toBe('new account')
  await act(async () => { await result.current.sendMessage('must remain locked') })
  expect(mocks.chat).toHaveBeenCalledTimes(2)
  await act(async () => { pendingChat.resolve(response('new')); await chat })
  expect(result.current.conversationId).toBe('new')
  for (const event of ['TOKEN_REFRESHED', 'SIGNED_IN', 'USER_UPDATED']) act(() => mocks.auth!(event, { user: { id: 'b' } }))
  expect(result.current.conversationId).toBe('new')
})
it('propagates price-change errors only through cart callback and sends explicit acceptance', async () => {
  const { result } = renderHook(() => useConcierge())
  const proposal = { id: 'p', validation: { status: 'PASS' } } as MealProposal
  mocks.action.mockRejectedValue(new Error('PRICE_CHANGED: 200000'))
  await act(async () => { await expect(result.current.addProposalToCart(proposal)).rejects.toThrow('PRICE_CHANGED') })
  await act(async () => { await expect(result.current.sendAction({ type: 'confirm_quote' })).resolves.toBe(false) })
  mocks.action.mockResolvedValue(response('accepted'))
  await act(async () => { await result.current.addProposalToCart(proposal, true) })
  expect(mocks.action.mock.calls.at(-1)?.[0].action).toEqual({ type: 'add_proposal_to_cart', proposal_id: 'p', accept_price_change: true })
})
it('discards in-flight chat on sign-out and does not unlock a newer anonymous request', async () => {
  const { result } = renderHook(() => useConcierge())
  act(() => mocks.auth!('SIGNED_IN', { user: { id: 'a' } }))
  const old = deferred<ConciergeResponseEnvelope>(); mocks.chat.mockReturnValue(old.promise)
  let oldChat!: Promise<void>; act(() => { oldChat = result.current.sendMessage('private') })
  act(() => mocks.auth!('SIGNED_OUT', null))
  const fresh = deferred<ConciergeResponseEnvelope>(); mocks.chat.mockReturnValue(fresh.promise)
  let freshChat!: Promise<void>; act(() => { freshChat = result.current.sendMessage('anonymous') })
  await act(async () => { old.resolve(response('private response')); await oldChat })
  expect(result.current.isLoading).toBe(true)
  expect(result.current.messages.some((message) => message.text.includes('private'))).toBe(false)
  await act(async () => { fresh.resolve(response('anonymous response')); await freshChat })
  expect(result.current.conversationId).toBe('anonymous response')
})
it('does not erase an already completed new-account conversation when an older reset finishes', async () => {
  const { result } = renderHook(() => useConcierge())
  await act(async () => { await result.current.sendMessage('hello') })
  const pending = deferred<ConciergeResponseEnvelope>(); mocks.action.mockReturnValue(pending.promise)
  let reset!: Promise<void>; act(() => { reset = result.current.resetConversation() })
  act(() => mocks.auth!('SIGNED_IN', { user: { id: 'new-user' } }))
  mocks.chat.mockResolvedValue(response('new account'))
  await act(async () => { await result.current.sendMessage('new') })
  await act(async () => { pending.resolve(response('reset')); await reset })
  expect(result.current.conversationId).toBe('new account')
  expect(result.current.messages.at(-1)?.text).toBe('new account')
})
